### ISSUE TITLE
remove duplicate chest and allow rotation

### ISSUE THREAD

**Issue by Stargateur** [Atria1234/WideChests#9]
Currently you can't rotate at 90° chess like 1x13 to 13x1, only 180°, it's would be nice to be able to, this would also reduce by 2 the number of coffer needed. Basically only have A>=B and have them rotate should work.

**Comment by Atria1234** [comment]
That is a limitation of the game as far as I know...unless there is some event which would allow me to check when someone tries to rotate them. But that would be very hands on approach and likely to lead to bugs.

**Comment by Stargateur** [comment]
but they is nothing to do rotate is on the game base, I'm quite new to factorio moding so can totally be wrong, but the only thing to handle is the merging, and so when you merge a 1x13 you just use a 13x1 and rotate it.

**Comment by Atria1234** [comment]
I meant the game doesn't support rotating chests. They just don't have the direction field attached to them.

**Comment by iPilot** [comment]
Well, actually, it is not a rotation, it is the matrix transpose. Chest itself keeps their direction or whatever.
It is slightly annoying to create vertically and horizontally oriented blueprints for train stations with merged chests - they cannot be flipped and in addition cannot be rotated for 90 degrees.
Is there a difference between rotating objects themselves and rotating their ghosts? If yes, then mod can support rotation for ghosts only, when we are absolutely sure that chests are empty.

**Comment by Atria1234** [comment]
It is a game limitation. Since containers can't be rotated (see second sentence in https://lua-api.factorio.com/latest/prototypes/ContainerPrototype.html) then game has no choice other than allow rotations only by 180° if you are trying to rotate entity which has different height/width. Game doesn't know that "when trying to rotate this 5x1 entity, replace it with this 1x5 entity", there's just no way to specify this.

Entity ghosts behave exactly same as their non-ghost variant.

Unless developers add support for rotating chests there is just no way how to do it. Only thing which could work is split all chests when you make a blueprint, but that also doesn't work 100% of the time.

**Comment by iPilot** [comment]
For the game engine merged chest are still chests and no events to handle for complex logic on rotating are fired as chests do not support rotation?

**Comment by Atria1234** [comment]
Correct
